apiVersion: apps/v1
kind: Deployment
metadata:
  name: laravel-app
  namespace: k8s
spec:
  revisionHistoryLimit: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  selector:
    matchLabels:
      app: k8s
  template:
    metadata:
      labels:
        app: k8s
        commit_hash: CICD_GIT_COMMIT
    spec:
      imagePullSecrets:
        - name: docker-registry
      containers:
        - name: laravel-app
          image: derpierre65/k8s-test:latest
          imagePullPolicy: Always
          volumeMounts:
            - mountPath: /var/www/html/storage/app/
              name: storage-volume
          ports:
            - containerPort: 80
          env:
            - name: CONTAINER_ROLE
              value: app
          envFrom:
            - secretRef:
                name: laravel-env
                optional: false
            - configMapRef:
                name: laravel-env
                optional: false
          startupProbe:
            periodSeconds: 1
            failureThreshold: 20
            successThreshold: 1
            timeoutSeconds: 1
            httpGet:
              scheme: HTTP
              path: /
              port: 80
      volumes:
        - name: storage-volume
          hostPath:
            path: /root/test/k8s-test.derpierre65.de/
            type: Directory
---
apiVersion: v1
kind: Service
metadata:
  name: laravel-app-service
  namespace: k8s
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  selector:
    app: k8s
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: k8s-ingress
  namespace: k8s
  annotations:
    kubernetes.io/ingress.class: traefik
    cert-manager.io/cluster-issuer: letsencrypt-staging
    traefik.ingress.kubernetes.io/router.middlewares: default-redirect-https@kubernetescrd
spec:
  tls:
  - hosts:
      - k8s-test.derpierre65.de
    secretName: k8s-tls
  rules:
    - host: k8s-test.derpierre65.de
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: laravel-app-service
                port:
                  number: 80